server:
  port: 8200

spring:
  datasource:
    url: jdbc:mysql://j5a201.p.ssafy.io:13306/beathub_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Beathub12!
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
<<<<<<< HEAD
      ddl-auto: update
=======
      ddl-auto: update
>>>>>>> e63d4dd6b63f962063accbb315066f4649353a56
